trigger:
    - master

jobs:
    - job: Autotests
      displayName: WebdriverIO Autotests Framework

      pool:
          vmImage: 'ubuntu-latest'

      steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
                versionSpec: '12.x'

          - script: |
                npm install
            displayName: 'Install dependencies required to run the tests'

          - script: |
                npm run selenium
            displayName: 'Starts the selenium hub and browser nodes in docker containers'

          - script: |
                npm run test && npm run report:ci || npm run report:ci
            displayName: 'Run tests'

          - task: CopyFiles@2
            displayName: Copy Allure Report
            inputs:
                SourceFolder: '$(System.DefaultWorkingDirectory)/report'
                Contents: '**'
                TargetFolder: '$(build.artifactstagingdirectory)/report'
            condition: succeededOrFailed()

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
                PathtoPublish: '$(build.artifactstagingdirectory)'
            condition: succeededOrFailed()
