version: 2
jobs:
    e2e-tests:
        docker:
            - image: circleci/node:10.16.3
        working_directory: ~/project

        steps:
            - checkout:
                  path: ~/project
            - run:
                  name: update-npm
                  command: sudo npm install -g npm@5
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: install-npm
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Starts the selenium hub and browser nodes in docker containers
                  command: npm run selenium
            - run:
                  name: Run tests and create allure report
                  command: npm run test && npm run report:ci || npm run report:ci
            - store_artifacts:
                  path: ~/project/report
workflows:
    e2e-tests:
        jobs:
            - e2e-tests
    version: 2
